# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',)},
        ),
    ]
