# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180624_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='genres',
            field=models.SmallIntegerField(choices=[(0, 'sport'), (1, 'cultura'), (2, 'country')], default=0),
        ),
    ]
