# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='genres',
            new_name='genre',
        ),
    ]
