# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_cultura_it_sport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='It',
            new_name='Country',
        ),
    ]
