# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180626_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='carddescription',
        ),
    ]
